version: '3.4'

services:
  stockportfolio.api:
    image: ${DOCKER_REGISTRY-}stockportfolioapi
    build:
      context: .
      dockerfile: StockPortfolio.API/Dockerfile
    ports:
      - 5400:80
      - 5401:443
    depends_on:
      - sqlserver

  sqlserver:
    restart: unless-stopped
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      MSSQL_SA_PASSWORD: "P@ssword123"
      ACCEPT_EULA: "Y"
    volumes:
      - "./data-mssql:/var/opt/mssql/data"
    ports:
      - 5050:1433

